_wandb:
    value:
        cli_version: 0.22.3
        e:
            db31muxea21xjxgpdz5s7a2imvhd5wly:
                codePath: train_xfirst.py
                codePathLocal: train_xfirst.py
                cpu_count: 288
                cpu_count_logical: 288
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "256654442496"
                        used: "17009475584"
                email: yzhan898@jh.edu
                executable: /u/yzhang116/.conda/envs/nn/bin/python3.10
                gpu: NVIDIA GH200 120GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "102625181696"
                      name: NVIDIA GH200 120GB
                      uuid: GPU-f0c4e4dd-0b89-e8d0-c0a8-953f5c447d5b
                host: gh009.hsn.cm.delta.internal.ncsa.edu
                memory:
                    total: "921330843648"
                os: Linux-6.4.0-150600.23.53-64kb-aarch64-with-glibc2.38
                program: /u/yzhang116/NN/quijote/train_xfirst.py
                python: CPython 3.10.19
                root: /u/yzhang116/NN/quijote
                slurm:
                    cluster_name: delta-gh
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpu_bind: quiet,mask_cpu:0x00000000000000000F000000000000000000000000000000000000000000000000000000
                    cpu_bind_list: 0x00000000000000000F000000000000000000000000000000000000000000000000000000
                    cpu_bind_type: 'mask_cpu:'
                    cpu_bind_verbose: quiet
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    distribution: cyclic
                    gpus_on_node: "1"
                    gpus_per_node: "1"
                    gtids: "0"
                    job_account: bdne-dtai-gh
                    job_cpus_per_node: "4"
                    job_end_time: "1776719911"
                    job_gid: "202"
                    job_group: grp_202
                    job_id: "2165276"
                    job_name: bash
                    job_nodelist: gh009
                    job_num_nodes: "1"
                    job_partition: ghx4
                    job_qos: bdne-dtai-gh
                    job_start_time: "1776718111"
                    job_uid: "90461"
                    job_user: yzhang116
                    jobid: "2165276"
                    launch_node_ipaddr: 172.28.80.8
                    localid: "0"
                    mem_per_node: "16384"
                    mpi_type: cray_shasta
                    network: single_node_vni,disable_rdzv_get
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: gh009
                    nprocs: "1"
                    ntasks: "1"
                    ntasks_per_node: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "35269"
                    pty_win_col: "80"
                    pty_win_row: "24"
                    srun_comm_host: 172.28.80.8
                    srun_comm_port: "39419"
                    step_gpus: "3"
                    step_id: "0"
                    step_launcher_port: "39419"
                    step_nodelist: gh009
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_resv_ports: 20173-20174
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /u/yzhang116
                    submit_host: gh-login02.delta.ncsa.illinois.edu
                    task_pid: "2650847"
                    tasks_per_node: "1"
                    topology_addr: deltaai_fabric.chassis_x8101c0.gh009
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=4
                    umask: "0077"
                startedAt: "2026-04-20T20:55:06.259585Z"
                writerId: db31muxea21xjxgpdz5s7a2imvhd5wly
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
                - 54
            "2":
                - 1
                - 41
                - 54
            "3":
                - 1
                - 13
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-aarch64
batch_size:
    value: 200
cnn_type:
    value: vit_cbam
dropout:
    value: 0
epochs:
    value: 1
gauss_delta:
    value: 0.1
job_id:
    value: 2165276
layers_types:
    value:
        - res_cbam
loss_type:
    value: cross_entropy
lr_max:
    value: 0.0001
lr_min:
    value: 1e-05
model:
    value: model_enc_dec_cos_xfirst
n_embd:
    value: 384
n_head:
    value: 12
n_heads_vit:
    value: 8
n_layer:
    value: 8
n_layers_vit:
    value: 4
patch_size:
    value: 4
